* Semester: Winter 2020

** Coolambury
  Link: https://github.com/michalloska/Coolambury
  
  Pictionary-like gam with desktop app (pyqt), and AI (a bot that uses neural networks to guess).
   
** Cookly
  https://github.com/cookly-PiTE/cookly
  
  Cooking recipies management. Made with django and mongo.
  
** Music Karaoke Django
  https://github.com/Peter2221/Music-Karaoke-DJango
  
  An online karaoke app, which automatically rates your performance with numpy.

** Cookit
  https://github.com/PiotrKolecki/cookitpiteproject
  
  Oline cooking cooking books

** Walk for the dog
  https://github.com/Equilibrium23/Walk-For-The-Dog
  
  Django app for matching dog owners with volunteers for dog walkers, with automatic dog breed recognition using neural networks.

** Kitchen
  https://github.com/mdmkl6/ProjectKitchen
  
  Project for managing resources in kitchen and making shopping lists, made with django.
  
  

* Semester: Summer 2020
** Project: Kryptonite
   Repo:https://github.com/maniekb/PitE-Project

** Project: EatGuesser
  Repo:https://github.com/kamilsudol/EatGuesser

** Project: Pampuch
   Repo: https://github.com/theYiome/pampuch

** Project: CovidLocalizations
  Repo: https://github.com/BlackDilvish/Movielity_Project

** Project: Arena-of-Heroes
  Repo:https://github.com/MichalKacprzak99/Arena-of-Heroes

** Project: Swarmball.ai
  Repo: https://github.com/Heecatee/Swarmball

** Project: Mood
  Repo: https://github.com/paulinajewulska/MOOD

** Project: Crypto_Price_Predictor
  Repo: https://github.com/KrystianKosek/Crypto_Price_Predictor

** Project: Jobaid
  Repo: https://github.com/Fadikk367/Jobaid

** Project: PyChord
  Repo: https://github.com/zuczeks/PyChord

** Project: iGarden
  Repo:  https://github.com/grzesiakm/iGarden

** Project: Fiszkily
  Repo: https://github.com/MichalLeszczynski/Fiszkily
